export const FETCH_CITIZENS_SUCCESS = "ETCH_CITIZENS_SUCCESS";
export const FETCH_CITIZENS_PENDING = "FETCH_CITIZENS_PENDING";
export const FETCH_CITIZENS_ERROR = "FETCH_CITIZENS_ERROR";
export const FETCH_CITIZENS_COUNT = 'FETCH_CITIZENS_COUNT';

export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const CLEAR_CITIZEN_NOTE = 'CLEAR_CITIZEN_NOTE';

export const ADD_NEW_CITIZEN = 'ADD_NEW_CITIZEN';

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';