export const FETCH_CITIZENS_SUCCESS = "ETCH_CITIZENS_SUCCESS";
export const FETCH_CITIZENS_PENDING = "FETCH_CITIZENS_PENDING";
export const FETCH_CITIZENS_ERROR = "FETCH_CITIZENS_ERROR";

export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';